# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/orl/Tianze_WS/Test_Control

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/orl/Tianze_WS/Test_Control

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/orl/Tianze_WS/Test_Control/CMakeFiles /home/orl/Tianze_WS/Test_Control//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/orl/Tianze_WS/Test_Control/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named standing_controlV2

# Build rule for target.
standing_controlV2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 standing_controlV2
.PHONY : standing_controlV2

# fast build rule for target.
standing_controlV2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/build
.PHONY : standing_controlV2/fast

#=============================================================================
# Target rules for targets named cmake_hello

# Build rule for target.
cmake_hello: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cmake_hello
.PHONY : cmake_hello

# fast build rule for target.
cmake_hello/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_hello.dir/build.make CMakeFiles/cmake_hello.dir/build
.PHONY : cmake_hello/fast

#=============================================================================
# Target rules for targets named standing_control

# Build rule for target.
standing_control: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 standing_control
.PHONY : standing_control

# fast build rule for target.
standing_control/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/build
.PHONY : standing_control/fast

#=============================================================================
# Target rules for targets named GeometricKinematicsTest

# Build rule for target.
GeometricKinematicsTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GeometricKinematicsTest
.PHONY : GeometricKinematicsTest

# fast build rule for target.
GeometricKinematicsTest/fast:
	$(MAKE) $(MAKESILENT) -f include/GeometricKinematics/CMakeFiles/GeometricKinematicsTest.dir/build.make include/GeometricKinematics/CMakeFiles/GeometricKinematicsTest.dir/build
.PHONY : GeometricKinematicsTest/fast

#=============================================================================
# Target rules for targets named geometric_kinematics_lib

# Build rule for target.
geometric_kinematics_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 geometric_kinematics_lib
.PHONY : geometric_kinematics_lib

# fast build rule for target.
geometric_kinematics_lib/fast:
	$(MAKE) $(MAKESILENT) -f include/GeometricKinematics/CMakeFiles/geometric_kinematics_lib.dir/build.make include/GeometricKinematics/CMakeFiles/geometric_kinematics_lib.dir/build
.PHONY : geometric_kinematics_lib/fast

#=============================================================================
# Target rules for targets named GeometricKinematicsMain

# Build rule for target.
GeometricKinematicsMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GeometricKinematicsMain
.PHONY : GeometricKinematicsMain

# fast build rule for target.
GeometricKinematicsMain/fast:
	$(MAKE) $(MAKESILENT) -f include/GeometricKinematics/CMakeFiles/GeometricKinematicsMain.dir/build.make include/GeometricKinematics/CMakeFiles/GeometricKinematicsMain.dir/build
.PHONY : GeometricKinematicsMain/fast

#=============================================================================
# Target rules for targets named kinematics_dynamics_lib

# Build rule for target.
kinematics_dynamics_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kinematics_dynamics_lib
.PHONY : kinematics_dynamics_lib

# fast build rule for target.
kinematics_dynamics_lib/fast:
	$(MAKE) $(MAKESILENT) -f include/AnalyticalKinematicsDynamics/CMakeFiles/kinematics_dynamics_lib.dir/build.make include/AnalyticalKinematicsDynamics/CMakeFiles/kinematics_dynamics_lib.dir/build
.PHONY : kinematics_dynamics_lib/fast

#=============================================================================
# Target rules for targets named kin_dyn_test

# Build rule for target.
kin_dyn_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kin_dyn_test
.PHONY : kin_dyn_test

# fast build rule for target.
kin_dyn_test/fast:
	$(MAKE) $(MAKESILENT) -f include/AnalyticalKinematicsDynamics/CMakeFiles/kin_dyn_test.dir/build.make include/AnalyticalKinematicsDynamics/CMakeFiles/kin_dyn_test.dir/build
.PHONY : kin_dyn_test/fast

libartl/artl.o: libartl/artl.c.o
.PHONY : libartl/artl.o

# target to build an object file
libartl/artl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/libartl/artl.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_hello.dir/build.make CMakeFiles/cmake_hello.dir/libartl/artl.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/libartl/artl.c.o
.PHONY : libartl/artl.c.o

libartl/artl.i: libartl/artl.c.i
.PHONY : libartl/artl.i

# target to preprocess a source file
libartl/artl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/libartl/artl.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_hello.dir/build.make CMakeFiles/cmake_hello.dir/libartl/artl.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/libartl/artl.c.i
.PHONY : libartl/artl.c.i

libartl/artl.s: libartl/artl.c.s
.PHONY : libartl/artl.s

# target to generate assembly for a file
libartl/artl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/libartl/artl.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_hello.dir/build.make CMakeFiles/cmake_hello.dir/libartl/artl.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/libartl/artl.c.s
.PHONY : libartl/artl.c.s

libartl/artl_internal.o: libartl/artl_internal.c.o
.PHONY : libartl/artl_internal.o

# target to build an object file
libartl/artl_internal.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/libartl/artl_internal.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_hello.dir/build.make CMakeFiles/cmake_hello.dir/libartl/artl_internal.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/libartl/artl_internal.c.o
.PHONY : libartl/artl_internal.c.o

libartl/artl_internal.i: libartl/artl_internal.c.i
.PHONY : libartl/artl_internal.i

# target to preprocess a source file
libartl/artl_internal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/libartl/artl_internal.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_hello.dir/build.make CMakeFiles/cmake_hello.dir/libartl/artl_internal.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/libartl/artl_internal.c.i
.PHONY : libartl/artl_internal.c.i

libartl/artl_internal.s: libartl/artl_internal.c.s
.PHONY : libartl/artl_internal.s

# target to generate assembly for a file
libartl/artl_internal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/libartl/artl_internal.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_hello.dir/build.make CMakeFiles/cmake_hello.dir/libartl/artl_internal.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/libartl/artl_internal.c.s
.PHONY : libartl/artl_internal.c.s

libartl/crc32c.o: libartl/crc32c.c.o
.PHONY : libartl/crc32c.o

# target to build an object file
libartl/crc32c.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/libartl/crc32c.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_hello.dir/build.make CMakeFiles/cmake_hello.dir/libartl/crc32c.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/libartl/crc32c.c.o
.PHONY : libartl/crc32c.c.o

libartl/crc32c.i: libartl/crc32c.c.i
.PHONY : libartl/crc32c.i

# target to preprocess a source file
libartl/crc32c.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/libartl/crc32c.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_hello.dir/build.make CMakeFiles/cmake_hello.dir/libartl/crc32c.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/libartl/crc32c.c.i
.PHONY : libartl/crc32c.c.i

libartl/crc32c.s: libartl/crc32c.c.s
.PHONY : libartl/crc32c.s

# target to generate assembly for a file
libartl/crc32c.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/libartl/crc32c.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_hello.dir/build.make CMakeFiles/cmake_hello.dir/libartl/crc32c.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/libartl/crc32c.c.s
.PHONY : libartl/crc32c.c.s

libartl/zstd/zstd.o: libartl/zstd/zstd.c.o
.PHONY : libartl/zstd/zstd.o

# target to build an object file
libartl/zstd/zstd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/libartl/zstd/zstd.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_hello.dir/build.make CMakeFiles/cmake_hello.dir/libartl/zstd/zstd.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/libartl/zstd/zstd.c.o
.PHONY : libartl/zstd/zstd.c.o

libartl/zstd/zstd.i: libartl/zstd/zstd.c.i
.PHONY : libartl/zstd/zstd.i

# target to preprocess a source file
libartl/zstd/zstd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/libartl/zstd/zstd.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_hello.dir/build.make CMakeFiles/cmake_hello.dir/libartl/zstd/zstd.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/libartl/zstd/zstd.c.i
.PHONY : libartl/zstd/zstd.c.i

libartl/zstd/zstd.s: libartl/zstd/zstd.c.s
.PHONY : libartl/zstd/zstd.s

# target to generate assembly for a file
libartl/zstd/zstd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/libartl/zstd/zstd.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_hello.dir/build.make CMakeFiles/cmake_hello.dir/libartl/zstd/zstd.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/libartl/zstd/zstd.c.s
.PHONY : libartl/zstd/zstd.c.s

lowlevelapi.o: lowlevelapi.c.o
.PHONY : lowlevelapi.o

# target to build an object file
lowlevelapi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/lowlevelapi.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_hello.dir/build.make CMakeFiles/cmake_hello.dir/lowlevelapi.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/lowlevelapi.c.o
.PHONY : lowlevelapi.c.o

lowlevelapi.i: lowlevelapi.c.i
.PHONY : lowlevelapi.i

# target to preprocess a source file
lowlevelapi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/lowlevelapi.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_hello.dir/build.make CMakeFiles/cmake_hello.dir/lowlevelapi.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/lowlevelapi.c.i
.PHONY : lowlevelapi.c.i

lowlevelapi.s: lowlevelapi.c.s
.PHONY : lowlevelapi.s

# target to generate assembly for a file
lowlevelapi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/lowlevelapi.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_hello.dir/build.make CMakeFiles/cmake_hello.dir/lowlevelapi.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/lowlevelapi.c.s
.PHONY : lowlevelapi.c.s

lowlevelapi_example.o: lowlevelapi_example.cpp.o
.PHONY : lowlevelapi_example.o

# target to build an object file
lowlevelapi_example.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_hello.dir/build.make CMakeFiles/cmake_hello.dir/lowlevelapi_example.cpp.o
.PHONY : lowlevelapi_example.cpp.o

lowlevelapi_example.i: lowlevelapi_example.cpp.i
.PHONY : lowlevelapi_example.i

# target to preprocess a source file
lowlevelapi_example.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_hello.dir/build.make CMakeFiles/cmake_hello.dir/lowlevelapi_example.cpp.i
.PHONY : lowlevelapi_example.cpp.i

lowlevelapi_example.s: lowlevelapi_example.cpp.s
.PHONY : lowlevelapi_example.s

# target to generate assembly for a file
lowlevelapi_example.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_hello.dir/build.make CMakeFiles/cmake_hello.dir/lowlevelapi_example.cpp.s
.PHONY : lowlevelapi_example.cpp.s

src/kin_left_arm.o: src/kin_left_arm.cpp.o
.PHONY : src/kin_left_arm.o

# target to build an object file
src/kin_left_arm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/src/kin_left_arm.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/src/kin_left_arm.cpp.o
.PHONY : src/kin_left_arm.cpp.o

src/kin_left_arm.i: src/kin_left_arm.cpp.i
.PHONY : src/kin_left_arm.i

# target to preprocess a source file
src/kin_left_arm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/src/kin_left_arm.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/src/kin_left_arm.cpp.i
.PHONY : src/kin_left_arm.cpp.i

src/kin_left_arm.s: src/kin_left_arm.cpp.s
.PHONY : src/kin_left_arm.s

# target to generate assembly for a file
src/kin_left_arm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/src/kin_left_arm.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/src/kin_left_arm.cpp.s
.PHONY : src/kin_left_arm.cpp.s

src/kin_right_arm.o: src/kin_right_arm.cpp.o
.PHONY : src/kin_right_arm.o

# target to build an object file
src/kin_right_arm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/src/kin_right_arm.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/src/kin_right_arm.cpp.o
.PHONY : src/kin_right_arm.cpp.o

src/kin_right_arm.i: src/kin_right_arm.cpp.i
.PHONY : src/kin_right_arm.i

# target to preprocess a source file
src/kin_right_arm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/src/kin_right_arm.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/src/kin_right_arm.cpp.i
.PHONY : src/kin_right_arm.cpp.i

src/kin_right_arm.s: src/kin_right_arm.cpp.s
.PHONY : src/kin_right_arm.s

# target to generate assembly for a file
src/kin_right_arm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/src/kin_right_arm.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/src/kin_right_arm.cpp.s
.PHONY : src/kin_right_arm.cpp.s

standing_control.o: standing_control.cpp.o
.PHONY : standing_control.o

# target to build an object file
standing_control.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/standing_control.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/standing_control.cpp.o
.PHONY : standing_control.cpp.o

standing_control.i: standing_control.cpp.i
.PHONY : standing_control.i

# target to preprocess a source file
standing_control.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/standing_control.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/standing_control.cpp.i
.PHONY : standing_control.cpp.i

standing_control.s: standing_control.cpp.s
.PHONY : standing_control.s

# target to generate assembly for a file
standing_control.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_controlV2.dir/build.make CMakeFiles/standing_controlV2.dir/standing_control.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/standing_control.dir/build.make CMakeFiles/standing_control.dir/standing_control.cpp.s
.PHONY : standing_control.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GeometricKinematicsMain"
	@echo "... GeometricKinematicsTest"
	@echo "... cmake_hello"
	@echo "... geometric_kinematics_lib"
	@echo "... kin_dyn_test"
	@echo "... kinematics_dynamics_lib"
	@echo "... standing_control"
	@echo "... standing_controlV2"
	@echo "... libartl/artl.o"
	@echo "... libartl/artl.i"
	@echo "... libartl/artl.s"
	@echo "... libartl/artl_internal.o"
	@echo "... libartl/artl_internal.i"
	@echo "... libartl/artl_internal.s"
	@echo "... libartl/crc32c.o"
	@echo "... libartl/crc32c.i"
	@echo "... libartl/crc32c.s"
	@echo "... libartl/zstd/zstd.o"
	@echo "... libartl/zstd/zstd.i"
	@echo "... libartl/zstd/zstd.s"
	@echo "... lowlevelapi.o"
	@echo "... lowlevelapi.i"
	@echo "... lowlevelapi.s"
	@echo "... lowlevelapi_example.o"
	@echo "... lowlevelapi_example.i"
	@echo "... lowlevelapi_example.s"
	@echo "... src/kin_left_arm.o"
	@echo "... src/kin_left_arm.i"
	@echo "... src/kin_left_arm.s"
	@echo "... src/kin_right_arm.o"
	@echo "... src/kin_right_arm.i"
	@echo "... src/kin_right_arm.s"
	@echo "... standing_control.o"
	@echo "... standing_control.i"
	@echo "... standing_control.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

